tap "burntsushi/ripgrep", "https://github.com/BurntSushi/ripgrep.git"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash"
brew "bat"
brew "cmake"
brew "ctags"
brew "ctop"
brew "dtrx"
brew "fish"
brew "gawk"
brew "git"
brew "htop"
brew "maven"
brew "neovim"
brew "pyenv"
brew "pyenv-virtualenv"
brew "sbt"
brew "stow"
brew "tig"
brew "tmux"
brew "vim", args: ["with-lua", "with-override-system-vi"]
brew "watch"
brew "burntsushi/ripgrep/ripgrep-bin"
